# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xa7a35tcpg236-1I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Maria/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Maria/Desktop/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/imports/nibbles/FullAdder.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/mux16to1.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/LogicUnitI.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/new/Detect_low.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/ArithmeticUnitI.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/Zero.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/Shifter.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/imports/files/Register16.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/mux16to1_16.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/LogicUnit.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/Decoder.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/Buf.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/ArithmeticUnit.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/RegisterFile.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/FunctionalUnit.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/DataMemory.vhd
  C:/Users/Maria/Desktop/project_1/project_1.srcs/sources_1/imports/sources_1/new/DataPath.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top DataPath -part xa7a35tcpg236-1I


write_checkpoint -force -noxdef DataPath.dcp

catch { report_utilization -file DataPath_utilization_synth.rpt -pb DataPath_utilization_synth.pb }
